branches:
    only:
        - travis
        - master

os: linux
distro: bionic
language: generic
services:
    - docker

script:
    - ( cd docker && ./build.sh )

after_success:
    - cat src/BUILD.LOG
    - >-
      [ "$TRAVIS_BRANCH" = "travis" -a "$TRAVIS_EVENT_TYPE" != "cron" ] &&
      wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh &&
      bash upload.sh src/PART.EXE

after_failure:
    - '[ -e src/BUILD.LOG ] && cat src/BUILD.LOG'

deploy:
  - on:
        branch: master
        condition: '"$TRAVIS_EVENT_TYPE" != "cron"'
        tags: true
    provider: releases
    file: src/PART.EXE 
    skip_cleanup: true
    api_key:
      secure: "D2nQCxydBfMJZVQI1cJ0TN5tAmEdo6t1EAqDZEdF2ddrBzzPake1ahF4Amye3Bq+hN8tv/EnWHAzAoT2grv0P2GtPuvrXg4bOtLsNHnTWIuDsTyC0PXNBsEf0UjpYOUGODCoVX75wy1yrw3Zwq3gF13UQQt7OLoVR0WC1rTv8azKW6dOehOmDo09Bw1OMrl9kN+qU2+2p2/hKgBVOJliLEr9z0Y9bqfX+iZjZ61hPfFhdcmRTkbPZm8DXUEB2rTQWc1H01KLEO5clMKGFr6iUss3hA4toL65+mViue+fPuGa3iWmuT3WxARVmWSUD9rtrtA37OPXLZXwigX9fhkHrsqkhKBwjcE3moaGhMXppAQZJt3esenf4m6V6u7J3EX6+Nqg+J3VbUopUGt+iIOeOsXip/loWcMNGCiyCNdcd3NtEp4HTGSvcwZr+weuRklfc4g3MSmsAOaRONBEw2mg7oxmpRL2P7Qj2vs+FGG8omzkudU0dVDzA2FoLCHjW2vxIamTLugtHMWHy84ML6QCJXaYDeqrTJ5OMdV76u43Y3dpX2jy9rcLTAOqq4gL3O3UkprnitIothYrTpyjKTIsbGK3+j+WMliMP58TRjvfzq2sMMyKkiwSh0SLxT4D4BHGVjgupURkYdWTwqb8g8gLUstdkx/oSalaJER8elzbVKs="
