#!/bin/sh

set -e

# Keep the log name in 8.3 format for DosBox
TMP_LOG="$(mktemp --suffix=.tmp -p "$SOURCEDIR" XXXXXXXX )"

trap 'rm -f "$TMP_LOG"' EXIT SIGTERM SIGQUIT SIGINT

(
    # Patch the configuration file to add explicit mounts for T: and S:
    # Also add output redirection for the real command
    while [ $# -ge 2 ]; do
        if [ "$1" = "-conf" ]; then
            CONF="$2"
            break
        fi
        shift
    done

    if [ -n "$CONF" ]; then
        # Note: the one-line 'a' command in sed scripts is a GNUism
        sed -i \
            -e "1a mount s $SOURCEDIR" \
            -e "1a mount t $TOOLSDIR" \
            -e 's/^\(T:\\[^[:blank:]]*\.EXE .*\)$/\1 >> S:\\'"${TMP_LOG##*/}"'/i' \
            "$CONF"
    fi
)

"$REALDOSBOX" "$@" >&2
cat "$TMP_LOG"
